#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("LayoutTest.Resource", IsApplication=true)]

namespace LayoutTest
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int selector = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050001
			public const int button1 = 2131034113;
			
			// aapt resource value: 0x7f05000d
			public const int button2 = 2131034125;
			
			// aapt resource value: 0x7f05000c
			public const int debugTextView = 2131034124;
			
			// aapt resource value: 0x7f050002
			public const int linearLayout1 = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int linearLayout2 = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int listView1 = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int listView2 = 2131034118;
			
			// aapt resource value: 0x7f050008
			public const int myButton = 2131034120;
			
			// aapt resource value: 0x7f05000a
			public const int textAge = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int textGender = 2131034123;
			
			// aapt resource value: 0x7f050009
			public const int textName = 2131034121;
			
			// aapt resource value: 0x7f050000
			public const int textView1 = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int textView2 = 2131034115;
			
			// aapt resource value: 0x7f050007
			public const int toggleButton1 = 2131034119;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int action_bar = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int cards_info = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int cards_info_row_inflate = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int cardslist = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int console_output = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int console_output_row_inflate = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int dialog_create = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int layout1 = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int layout_row = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int Main = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int sessions = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int sessions_row_inflate = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int setting = 2130903052;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
